export { default as HomeLayout } from './HomeLayout';
export { default as Landing, loader as landingLoader } from './Landing';
export { default as SingleProduct, loader as singleProductLoader } from './SingleProduct';
export { default as Products, loader as productsLoader } from './Products';
export { default as Cart } from './Cart';
export { default as Error } from './Error';
export { default as About } from './About';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Checkout, loader as checkoutLoader  } from './Checkout';
export { default as Orders, loader as ordersLoader } from './Orders';
